### ISSUE TITLE
[VENDOR REQUEST]: The Pihut (UK)

### ISSUE THREAD

**Issue by PhillippOhlandt** [nerves-metal-detector/nerves_metal_detector#28]
### Vendor Name

The Pihut

### Vendor Country

UK

### Vendor URL

https://thepihut.com/

### Product Links

https://rpilocator.com/?vendor=thepihut

### Additional information

https://github.com/nerves-metal-detector/nerves_metal_detector/blob/master/CONTRIBUTING.md#adding-new-vendors-and-products-from-rpilocator

**Comment by bflatau** [comment]
@PhillippOhlandt I'll give this one a shot next.

**Comment by PhillippOhlandt** [comment]
@bflatau Yes, sure! Name the vendor `ThePiHut`.

**Comment by PhillippOhlandt** [comment]
Oh that one is interesting. It uses the `<script type="application/ld+json">` tag with json data. We already have vendors that parse these. The only difference here is that it lists all variants in the `offers` field even when you request a specific variant via url. That means you must find the correct item in that list based on the url.
