### ISSUE TITLE
[VENDOR REQUEST]: Chicago Electronic Distributors (US)

### ISSUE THREAD

**Issue by PhillippOhlandt** [nerves-metal-detector/nerves_metal_detector#29]
### Vendor Name

Chicago Elec. Dist.

### Vendor Country

US

### Vendor URL

https://chicagodist.com/

### Product Links

https://rpilocator.com/?vendor=chicagodist

### Additional information

https://github.com/nerves-metal-detector/nerves_metal_detector/blob/master/CONTRIBUTING.md#adding-new-vendors-and-products-from-rpilocator

**Comment by bflatau** [comment]
I submitted a PR for this one. I was testing the digikey to see if I was having issues pulling info in general and this one seemed easy enough to implement.
