### ISSUE TITLE
[VENDOR REQUEST]: Sparkfun (US)

### ISSUE THREAD

**Issue by PhillippOhlandt** [nerves-metal-detector/nerves_metal_detector#34]
### Vendor Name

Sparkfun

### Vendor Country

US

### Vendor URL

https://www.sparkfun.com/

### Product Links

https://rpilocator.com/?vendor=sparkfun

### Additional information

https://github.com/nerves-metal-detector/nerves_metal_detector/blob/master/CONTRIBUTING.md#adding-new-vendors-and-products-from-rpilocator

**Comment by bflatau** [comment]
I'll try tackling this in the next day or so, if that's OK?

**Comment by PhillippOhlandt** [comment]
@bflatau Yes, sure! You can copy e.g. the `PiShopCh` vendor and adjust the module name and vendor info. The actual scraping code should work just fine for Sparkfun.
